services:
  - type: web
    name: safedrive-pro-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here as needed
